const stories=[
  {category:"History Made",title:"Thomas chooses Universidad México",body:"Jordan Thomas takes the Panteras job as UMX becomes the NCAA's first non-U.S. member, backed by player transfers from sister school UCLA.",meta:"5 MIN READ · BREAKING"},
  {category:"Desert Bound",title:"Chris Cathcart accepts Arizona job",body:"Cathcart is heading to Tucson with a spread-tempo vision and a mandate to turn the Wildcats into contenders.",meta:"3 MIN READ · COACHING CAROUSEL"},
  {category:"New Era",title:"Glenn Vernon takes over at Duke",body:"Vernon brings energy and a balanced attack to Durham as the Blue Devils launch an ambitious culture rebuild.",meta:"3 MIN READ · COACHING CAROUSEL"},
  {category:"Decision Watch",title:"Dustin Cathcart remains on the market",body:"One of the carousel's most intriguing candidates is still evaluating openings and has not committed to a program.",meta:"2 MIN READ · DEVELOPING"},
  {category:"Breaking News",title:"Sam Small chooses South Carolina",body:"The defending national champion is returning to his family's South Carolina roots to lead the Gamecocks into a new era.",meta:"JUST IN · THE DECISION IS FINAL"}
];
const heroSlides=[
  {tag:"Breaking News",title:"SAM CHOOSES|SOUTH CAROLINA.",summary:"The defending national champion opens the evidence bag and returns to his family's South Carolina roots.",image:"assets/coaches/sam-small-decision.png",position:"center 25%"},
  {tag:"History Made",title:"THOMAS TAKES|FOOTBALL GLOBAL.",summary:"Jordan Thomas leads Universidad México into the NCAA as the first program from outside the United States.",image:"assets/coaches/jordan-thomas-umx-v2.png",position:"center 24%"},
  {tag:"Desert Bound",title:"THE NEW SCHOOL|HITS ARIZONA.",summary:"Chris Cathcart takes his 104-play tempo experiment to Tucson—and promises the old guard will feel every snap.",image:"assets/coaches/chris-cathcart-arizona.png",position:"center 22%"},
  {tag:"Blueprint Era",title:"GLENN BUILDS|A NEW DUKE.",summary:"The quiet craftsman brings the Cordless Drill offense and Table Saw package to Durham.",image:"assets/coaches/glenn-vernon-duke.png",position:"center 20%"},
  {tag:"Decision Watch",title:"WHO WILL HIRE|DUSTY?",summary:"The MacGyver of the Marines remains the carousel's most inventive—and unpredictable—available coach.",image:"assets/coaches/dustin-cathcart-open-to-work.png",position:"center 22%"}
];
const rankings=[
  [1,"Indiana","16–0","—"],[2,"Miami","13–3","▲ 8"],[3,"Ole Miss","13–2","▲ 3"],[4,"Oregon","13–2","▲ 1"],[5,"Ohio State","12–2","▼ 2"],[6,"Georgia","12–2","▼ 4"],[7,"Texas Tech","12–2","▼ 3"],[8,"Texas A&M","11–2","▼ 1"],[9,"Alabama","11–4","▲ 2"],[10,"Notre Dame","10–2","▼ 1"]
];
const scores=[
  ["FINAL","Charlotte Cobras",26,"Gastonia Gators",20],["FINAL","Mint Hill Mustangs",34,"Matthews Marauders",6],["FINAL / OT","Queen City Raptors",14,"Concord Crushers",13],["FINAL","Pineville Pirates",22,"Rock Hill Rockets",24]
];
const players=[
  {rank:1,name:"C.J. Carr",school:"QB · NOTRE DAME",odds:"+750",status:"Co-favorite",case:"Efficient returning starter with an NFL-caliber ceiling and a schedule built for a national awards run."},
  {rank:2,name:"Arch Manning",school:"QB · TEXAS",odds:"+750",status:"Co-favorite",case:"Football royalty gets another shot at converting elite talent, massive exposure, and Texas expectations into a Heisman season."},
  {rank:3,name:"Trinidad Chambliss",school:"QB · OLE MISS",odds:"+900",status:"Top challenger",case:"The sixth-year quarterback enters 2026 with playoff experience, explosive upside, and the shortest odds behind the two favorites."}
];
// COACH PROFILES — edit these fields to update the Coaches section.
const coaches=[
  {name:"Dustin “Dusty” Cathcart",team:"Coaching Market",role:"Head Coach Candidate",image:"assets/coaches/dustin-cathcart-open-to-work.png",record:"Available",scheme:"MacGyver multiple",background:"Marine legend says Dusty once repaired a communications truck with a paper clip, an energy-drink tab, and language too classified for television. He now designs offenses the same way: broken parts go in, touchdowns come out.",storyline:"His 700-page playbook is rumored to include formations named Classified, Warranty Void, and Ask Jordan What Happened Last Time."},
  {name:"Chris Cathcart",team:"Arizona",role:"Head Coach",image:"assets/coaches/chris-cathcart-arizona.png",record:"First season",scheme:"Next-gen tempo",background:"Chris allegedly learned to identify Cover 2 before he learned long division. Raised at the intersection of Marine ingenuity and backyard trash talk, he built Arizona's tempo system on a gaming console Dusty confiscated in 2009.",storyline:"He respects the old guard. He also plans to run 104 plays per game until every uncle, father, and family friend admits the kid was right."},
  {name:"Glenn Vernon",team:"Duke",role:"Head Coach",image:"assets/coaches/glenn-vernon-duke.png",record:"First season",scheme:"Blueprint offense",background:"They called him Kobe because he looked like the legend and once scored 81 in a Charlotte rec game—although the only surviving box score is written on a Bojangles napkin. Glenn later designed Duke's offense while wandering the lumber aisle at 2 a.m.",storyline:"Every formation is named after a power tool. Opponents still haven't solved the Cordless Drill, and NCAA officials refuse to inspect the Table Saw package."},
  {name:"Jordan Thomas",team:"Universidad México",role:"Head Coach",image:"assets/coaches/jordan-thomas-umx-v2.png",record:"Inaugural season",scheme:"Expeditionary power spread",background:"Jordan crossed borders, oceans, and enough Marine obstacle courses to treat fourth-and-goal as light cardio. He accepted the UMX job after allegedly sketching the Panteras' first playbook on the back of an international flight safety card.",storyline:"UCLA is sending players, Mexico City is building a legend, and Jordan claims the altitude is merely a defensive coordinator who cannot be fired."},
  {name:"Sam Small",team:"South Carolina",role:"Head Coach",image:"assets/coaches/sam-small-decision.png",record:"Reigning national champ",scheme:"Law-and-order defense",background:"Sam transformed lessons from asset protection, corrections, and police work into the nation's strictest defense. After winning the national title, he chose to return to his family's South Carolina roots and take command of the Gamecocks.",storyline:"The evidence bag is open. The Decision is final. The champion is taking his talents—and the cursed headset rumors—to Columbia."}
];
const lore=[
  {year:"Charlotte",title:"The Napkin Pact",body:"Jordan, Glenn, and Sam supposedly swear eternal brotherhood over a Bojangles napkin—the same disputed document containing Glenn's legendary 81-point box score and the first draft of Sam's championship defense."},
  {year:"The Marines",title:"Operation: Best Friend",body:"Dusty offers Jordan friendship so relentlessly it becomes a campaign with phases, logistics, and after-action reports. Jordan finally surrenders. The treaty has never been broken, though rivalry week routinely tests it."},
  {year:"The Family",title:"The Backyard Combine",body:"Chris grows up inside an unofficial coaching laboratory where cookouts become film sessions and every family argument ends with somebody drawing a route tree. Jordan serves as uncle, scout, and occasional target of the kid's trash talk."},
  {year:"The Dynasty",title:"The Headset Prophecy",body:"An allegedly cursed headset passes through the brotherhood. Whoever wears it can win a title—but must eventually defeat somebody from the circle. Sam won first. Now everyone wants the headset and nobody admits possessing it."}
];
const articles=[
  {category:"Staff Move",date:"July 16, 2026",read:"4 min",title:"Jordan Thomas hires Nick O'Leary for one extremely personal assignment",dek:"The former Florida State standout joins the UMX staff with a normal coaching title—and one responsibility written entirely in quotation marks.",body:["Universidad México head coach Jordan Thomas has recruited former Florida State player Nick O'Leary to join the Panteras as an assistant coach. Officially, O'Leary will help install a physical offensive identity and bring championship-level toughness to the inaugural program.","Unofficially, sources say his primary responsibility is to locate Coach Dusty Cathcart at dynasty events, maintain uncomfortable eye contact, and ask a single question: ‘Remember what happened last time?’ Neither Jordan nor O'Leary has explained what happened last time. Dusty reportedly knows, refuses to discuss it, and has already added a formation called Selective Memory to his classified playbook." ]},
  {category:"Portal Watch",date:"July 16, 2026",read:"6 min",title:"The UCLA-to-UMX airlift has officially begun",dek:"Forty-seven equipment trunks, two quarterbacks, and one suspiciously large playbook were spotted boarding a charter flight to Mexico City.",body:["What began as a gracious partnership between sister schools has become the boldest roster experiment in college football. UCLA staffers insist the transfers are voluntary; JNN sources say the Panteras' altitude-adjusted taco Tuesdays closed several commitments before the plane left Los Angeles.","Coach Jordan Thomas declined to reveal his opening depth chart, saying only that every player who survives the first Mexico City conditioning test will receive oxygen, a locker, and the opportunity to make international history."]},
  {category:"JNN Investigation",date:"July 16, 2026",read:"8 min",title:"Who has the cursed championship headset?",dek:"Sam Small won the national title wearing it. By sunrise, the headset had vanished—and all four of his oldest rivals deny touching it.",body:["Security footage shows a figure leaving the stadium with a headset-shaped object, a Bojangles bag, and what experts believe may be Glenn Vernon's disputed 81-point napkin. The image is too grainy for identification, but Dusty has already produced a working replica from a toaster and two radio parts.","League investigators consider the curse unproven. Nevertheless, three equipment managers have requested transfers, Chris Cathcart refuses to wear wireless audio, and Jordan Thomas says the Panteras communicate exclusively through Marine hand signals."]},
  {category:"Recruiting",date:"July 15, 2026",read:"4 min",title:"Five-star quarterback commits to whichever school hires Dusty",dek:"The nation's most unpredictable recruit has attached his future to a coach who still has not selected his own future.",body:["The announcement sent athletic directors scrambling to find Dusty's number, though reports indicate he changes phones whenever someone asks to see the Classified formation. One booster has offered a private jet; another reportedly mailed him an unopened toolbox as a sign of respect.","Dusty remains publicly undecided. Privately, JNN has learned he has ranked every opening by offensive-line depth, cafeteria quality, and whether the facilities department will let him rewire the scoreboard himself."]},
  {category:"Campus Report",date:"July 14, 2026",read:"5 min",title:"Duke installs power-tool warning system at practice",dek:"The Cordless Drill formation is legal. The Table Saw package remains under review.",body:["Glenn Vernon's first closed practice triggered noise complaints from two counties and a formal inquiry from the equipment committee. Duke maintains the sounds were cadence calls. Nearby residents insist they heard an impact driver on third-and-seven.","Vernon calmly denied bringing actual power tools onto the field, then completed the press conference by repairing a broken podium without looking down. Duke scored three touchdowns during the distraction."]},
  {category:"Breaking News",date:"July 16, 2026",read:"7 min",title:"Evidence bag opened: Sam Small is returning to South Carolina",dek:"The defending national champion has made his decision. Family roots, a home-state challenge, and one very dramatic reveal are bringing him to Columbia.",body:["After weeks of secrecy, notarized paperwork, and a coaching search conducted with the intensity of a criminal investigation, Sam Small opened the evidence bag and revealed South Carolina. The move brings the reigning national champion back to the state where his family roots run deepest.","The Gamecocks are getting Sam's law-and-order defense, championship standard, and whatever supernatural advantage may remain inside the missing headset. Jordan congratulated his oldest friend. Glenn began revising the Blueprint. Chris posted a single rooster emoji. Dusty reportedly asked whether the evidence bag was reusable."]},
  {category:"Folklore",date:"July 12, 2026",read:"3 min",title:"Scientists date the Bojangles napkin to the Charlotte era",dek:"The artifact may prove Glenn scored 81—or merely ordered 81 Bo-Rounds.",body:["Carbon testing confirms the napkin is old enough to come from the brotherhood's middle-school years. Handwriting experts found traces of a box score, three offensive formations, and the phrase Jordan owes me five dollars.","Glenn considers the case closed. Sam wants a second opinion. Jordan says the napkin's real importance is the pact written on the reverse: when the five friends eventually controlled college football, none would duck the smoke."]}
];
const socialPosts=[
  {name:"JNN Breaking News",handle:"@JNNBreaking",time:"NOW",avatar:"J!",text:"THE DECISION IS IN: Defending national champion Sam Small is returning to South Carolina to become head coach of the Gamecocks.",tags:"#WelcomeHomeSam #Gamecocks"},
  {name:"UMX Staff Tracker",handle:"@PanterasDesk",time:"1m",avatar:"UM",text:"Jordan Thomas has hired former FSU player Nick O'Leary as an assistant. Job duties reportedly include finding Dusty and asking: ‘Remember what happened last time?’",tags:"#UMX #RememberLastTime"},
  {name:"Dynasty Sources",handle:"@JNNInsider",time:"4m",avatar:"DS",text:"Mystery solved: the black SUVs were headed south. Sam Small's evidence bag contained a South Carolina contract.",tags:"#TheDecision #SpursUp"},
  {name:"UMX Football",handle:"@UMXPanteras",time:"18m",avatar:"UM",text:"First practice in Ciudad de México. Coach Thomas called the altitude ‘a coordinator who can't be fired’ and then scheduled twelve more sprints.",tags:"#VamosPanteras"},
  {name:"Arizona After Dark",handle:"@DesertDynasty",time:"31m",avatar:"AZ",text:"Chris Cathcart's offense completed a full drive before our photographer finished changing lenses. The kid might actually run 104 plays a game.",tags:"#BearDown #NewSchool"},
  {name:"Duke Equipment",handle:"@BlueDevilTools",time:"52m",avatar:"DU",text:"For legal reasons, the sound heard at practice was NOT a table saw. No further questions at this time.",tags:"#CordlessDrill"},
  {name:"Portal Watch",handle:"@PortalAfterDark",time:"1h",avatar:"PW",text:"UCLA-to-UMX charter manifest: 42 players, 7 coaches, 63 bags, and one crate labeled DO NOT OPEN ABOVE 7,000 FEET.",tags:"#PortalSeason"},
  {name:"Recruiting Rumors",handle:"@FiveStarSmoke",time:"2h",avatar:"5★",text:"The five-star QB tied to Dusty Cathcart just followed 19 schools, unfollowed all 19, then posted a picture of a toolbox.",tags:"#MacGyverMultiple"},
  {name:"Charlotte Lore",handle:"@QueenCityFilm",time:"3h",avatar:"CL",text:"Independent lab confirms the Bojangles napkin is authentic. Still unclear whether Glenn scored 81 or ordered 81 Bo-Rounds.",tags:"#NapkinGate"},
  {name:"Headset Tracker",handle:"@CursedHeadset",time:"5h",avatar:"🎧",text:"Location: unknown. Battery: 87%. Curse: active. Rivalry week is going to be cinema.",tags:"#BrotherhoodBeforeFootball"}
];
const tickers=["BREAKING: National champion Sam Small chooses South Carolina","THE DECISION IS FINAL — the Gamecocks land the reigning champ","HISTORY: Universidad México becomes NCAA's first non-U.S. member","Coach Jordan Thomas introduced as leader of the Panteras"];
heroSlides[0].image="assets/coaches/sam-small-decision.png?v=20260716-2";
coaches.find(coach=>coach.name==="Sam Small").image="assets/coaches/sam-small-decision.png?v=20260716-2";
const orderedStories=[...stories].sort((a,b)=>(b.category==="Breaking News")-(a.category==="Breaking News"));
document.querySelector('#story-grid').innerHTML=orderedStories.map(s=>`<article class="story-card"><span class="category">${s.category}</span><h3>${s.title}</h3><p>${s.body}</p><span class="story-meta">${s.meta}</span></article>`).join('');
const topStorySlugs={"Sam Small chooses South Carolina":"sam-small-south-carolina","Thomas chooses Universidad México":"jordan-thomas-universidad-mexico","Chris Cathcart accepts Arizona job":"chris-cathcart-arizona","Glenn Vernon takes over at Duke":"glenn-vernon-duke","Dustin Cathcart remains on the market":"dusty-cathcart-decision-watch"};
document.querySelector('#story-grid').innerHTML=orderedStories.map(s=>`<a class="story-card" href="article.html?story=${topStorySlugs[s.title]}"><span class="category">${s.category}</span><h3>${s.title}</h3><p>${s.body}</p><span class="story-meta">${s.meta} · READ STORY →</span></a>`).join('');
document.querySelector('#rankings-list').innerHTML=rankings.map(([p,t,r,tr])=>`<div class="rank-row"><span class="pos">${p}</span><b>${t}</b><small>${r}</small><span class="trend ${tr.includes('▲')?'up':tr.includes('▼')?'down':''}">${tr}</span></div>`).join('');
document.querySelector('#score-list').innerHTML=scores.map(([s,a,as,b,bs])=>`<article class="score-card"><span class="status">${s}</span><div class="score-team"><strong>${a}</strong><b>${as}</b></div><div class="score-team"><strong>${b}</strong><b>${bs}</b></div></article>`).join('');
document.querySelector('#player-grid').innerHTML=players.map(p=>`<article class="player-card" data-rank="${p.rank}"><span class="school">${p.school}</span><h3>${p.name}</h3><p>${p.case}</p><div class="stats"><span><b>${p.odds}</b><small>Preseason odds</small></span><span><b>${p.status}</b><small>Market status</small></span><span><b>2026</b><small>Season</small></span></div></article>`).join('');
document.querySelector('#coach-grid').innerHTML=coaches.map(c=>`<article class="coach-card"><div class="coach-photo"><img src="${c.image}" alt="${c.name}, ${c.team} ${c.role}" loading="lazy"><span>${c.team}</span></div><div class="coach-copy"><p class="coach-role">${c.role}</p><h3>${c.name}</h3><p class="coach-background">${c.background}</p><div class="coach-facts"><span><small>Record</small><b>${c.record}</b></span><span><small>Identity</small><b>${c.scheme}</b></span></div><blockquote>“${c.storyline}”</blockquote></div></article>`).join('');
document.querySelector('#connection-map').innerHTML=`<span>Jordan</span><i>Charlotte</i><span>Glenn</span><i>Charlotte</i><span>Sam</span><i>Marines</i><span>Dusty</span><i>Family</i><span>Chris</span>`;
document.querySelector('#lore-grid').innerHTML=lore.map((l,i)=>`<article class="lore-card"><span class="lore-number">0${i+1}</span><p>${l.year}</p><h3>${l.title}</h3><div>${l.body}</div></article>`).join('');
document.querySelector('#article-grid').innerHTML=articles.map((a,i)=>`<details class="article-card" ${i===0?'open':''}><summary><span class="article-index">0${i+1}</span><span class="article-category">${a.category}</span><h3>${a.title}</h3><p>${a.dek}</p><span class="article-meta">${a.date} · ${a.read} read</span><span class="article-action"><b>Read story</b><i>+</i></span></summary><div class="article-body">${a.body.map(p=>`<p>${p}</p>`).join('')}</div></details>`).join('');
document.querySelector('#article-grid').innerHTML=articles.map((a,i)=>`<a class="article-card" href="article.html?story=desk-${i}"><span class="article-index">0${i+1}</span><span class="article-category">${a.category}</span><h3>${a.title}</h3><p>${a.dek}</p><span class="article-meta">${a.date} · ${a.read} read</span><span class="article-action"><b>Read full story</b><i>→</i></span></a>`).join('');
document.querySelector('#social-posts').innerHTML=socialPosts.map(p=>`<article class="social-post"><div class="social-avatar">${p.avatar}</div><div><div class="social-byline"><b>${p.name}</b><span>${p.handle} · ${p.time}</span></div><p>${p.text}</p><a href="#articles" aria-label="Fictional hashtag">${p.tags}</a><div class="social-actions" aria-hidden="true"><span>♡</span><span>↻</span><span>↗</span></div></div></article>`).join('');
const socialStorySlugs=["sam-small-south-carolina","desk-0","sam-small-south-carolina","jordan-thomas-universidad-mexico","chris-cathcart-arizona","glenn-vernon-duke","desk-1","desk-3","desk-6","desk-2"];
document.querySelectorAll('#social-posts .social-post a').forEach((link,index)=>{link.href=`article.html?story=${socialStorySlugs[index]}`;link.setAttribute('aria-label','Read related JNN story')});
const mobilePosts=[...socialPosts,...socialPosts];
document.querySelector('#mobile-social-track').innerHTML=mobilePosts.map(p=>`<span><b>${p.handle}</b> ${p.text} <i>${p.tags}</i></span>`).join('');
const heroImage=document.querySelector('#hero-image'),heroTag=document.querySelector('#hero-tag'),heroTitle=document.querySelector('#hero-title'),heroSummary=document.querySelector('#hero-summary'),heroDots=document.querySelector('#hero-dots'),heroStory=document.querySelector('.lead-story');
let heroIndex=0,heroTimer;
const heroStorySlugs=["sam-small-south-carolina","jordan-thomas-universidad-mexico","chris-cathcart-arizona","glenn-vernon-duke","dusty-cathcart-decision-watch"];
document.querySelector('#hero-link').addEventListener('click',event=>{event.preventDefault();location.href=`article.html?story=${heroStorySlugs[heroIndex]}`});
heroDots.innerHTML=heroSlides.map((_,i)=>`<button aria-label="Show story ${i+1}" data-slide="${i}"><span>0${i+1}</span></button>`).join('');
function showHero(index){heroIndex=(index+heroSlides.length)%heroSlides.length;const slide=heroSlides[heroIndex];heroStory.classList.add('is-changing');setTimeout(()=>{heroImage.src=slide.image;heroImage.style.objectPosition=slide.position;heroTag.textContent=slide.tag;const [line1,line2]=slide.title.split('|');heroTitle.innerHTML=`${line1}<br><span>${line2}</span>`;heroSummary.textContent=slide.summary;heroDots.querySelectorAll('button').forEach((dot,i)=>dot.classList.toggle('active',i===heroIndex));heroStory.classList.remove('is-changing')},180)}
function startHero(){clearInterval(heroTimer);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)heroTimer=setInterval(()=>showHero(heroIndex+1),7000)}
document.querySelector('#hero-prev').addEventListener('click',()=>{showHero(heroIndex-1);startHero()});document.querySelector('#hero-next').addEventListener('click',()=>{showHero(heroIndex+1);startHero()});heroDots.addEventListener('click',e=>{const dot=e.target.closest('button');if(dot){showHero(Number(dot.dataset.slide));startHero()}});heroStory.addEventListener('mouseenter',()=>clearInterval(heroTimer));heroStory.addEventListener('mouseleave',startHero);heroStory.addEventListener('focusin',()=>clearInterval(heroTimer));heroStory.addEventListener('focusout',startHero);showHero(0);startHero();
let heroTouchStart=0;
heroStory.addEventListener('touchstart',e=>{heroTouchStart=e.changedTouches[0].clientX},{passive:true});
heroStory.addEventListener('touchend',e=>{const distance=e.changedTouches[0].clientX-heroTouchStart;if(Math.abs(distance)>50){showHero(heroIndex+(distance<0?1:-1));startHero()}},{passive:true});
const ticker=[...tickers,...tickers].map(t=>`<span>${t}</span>`).join('');document.querySelector('#ticker-track').innerHTML=ticker;
const now=new Date();document.querySelector('#date-stamp').textContent=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase();document.querySelector('#year').textContent=now.getFullYear();
const button=document.querySelector('.menu-button'),links=document.querySelector('.nav-links');button.addEventListener('click',()=>{const open=links.classList.toggle('open');button.setAttribute('aria-expanded',open)});links.addEventListener('click',()=>{links.classList.remove('open');button.setAttribute('aria-expanded','false')});
