const stories=[
  {category:"History Made",title:"Thomas chooses Universidad México",body:"Jordan Thomas takes the Panteras job as UMX becomes the NCAA's first non-U.S. member, backed by player transfers from sister school UCLA.",meta:"5 MIN READ · BREAKING"},
  {category:"Desert Bound",title:"Chris Cathcart accepts Arizona job",body:"Cathcart is heading to Tucson with a spread-tempo vision and a mandate to turn the Wildcats into contenders.",meta:"3 MIN READ · COACHING CAROUSEL"},
  {category:"New Era",title:"Glenn Vernon takes over at Duke",body:"Vernon brings energy and a balanced attack to Durham as the Blue Devils launch an ambitious culture rebuild.",meta:"3 MIN READ · COACHING CAROUSEL"},
  {category:"Decision Watch",title:"Dustin Cathcart remains on the market",body:"One of the carousel's most intriguing candidates is still evaluating openings and has not committed to a program.",meta:"2 MIN READ · DEVELOPING"},
  {category:"The Decision",title:"Champion Sam Small will choose a new school",body:"Last season's national championship coach is leaving for a new challenge. His destination remains secret as the dynasty awaits his announcement.",meta:"BREAKING · CHAMPS GO WHERE THEY WANT"}
];
const rankings=[
  [1,"Ohio State","7–0","—"],[2,"Metro State","7–0","▲ 2"],[3,"Georgia","6–1","▼ 1"],[4,"Oregon","6–1","▲ 1"],[5,"LSU","6–1","▼ 2"],[6,"Texas","5–2","—"],[7,"Penn State","6–1","▲ 3"],[8,"Miami","5–2","▼ 1"],[9,"Clemson","5–2","NEW"],[10,"Alabama","4–3","▼ 2"]
];
const scores=[
  ["FINAL","#2 Metro State",38,"#11 Coastal Tech",31],["FINAL / OT","#5 LSU",27,"#14 Florida",24],["FINAL","#1 Ohio State",45,"Wisconsin",17],["FINAL","#9 Clemson",20,"#6 Texas",34]
];
const players=[
  [1,"MARCUS REED","QB · METRO STATE","2,814","28","71%"],[2,"JALEN CROSS","HB · OHIO STATE","1,226","16","7.4"],[3,"DANTE WILLIAMS","WR · OREGON","1,087","12","18.1"]
];
// COACH PROFILES — edit these fields to update the Coaches section.
const coaches=[
  {name:"Dustin “Dusty” Cathcart",team:"Coaching Market",role:"Head Coach Candidate",image:"assets/coaches/dustin-cathcart-open-to-work.png",record:"Available",scheme:"MacGyver multiple",background:"Marine legend says Dusty once repaired a communications truck with a paper clip, an energy-drink tab, and language too classified for television. He now designs offenses the same way: broken parts go in, touchdowns come out.",storyline:"His 700-page playbook is rumored to include formations named Classified, Warranty Void, and Ask Jordan What Happened Last Time."},
  {name:"Chris Cathcart",team:"Arizona",role:"Head Coach",image:"assets/coaches/chris-cathcart-arizona.png",record:"First season",scheme:"Next-gen tempo",background:"Chris allegedly learned to identify Cover 2 before he learned long division. Raised at the intersection of Marine ingenuity and backyard trash talk, he built Arizona's tempo system on a gaming console Dusty confiscated in 2009.",storyline:"He respects the old guard. He also plans to run 104 plays per game until every uncle, father, and family friend admits the kid was right."},
  {name:"Glenn Vernon",team:"Duke",role:"Head Coach",image:"assets/coaches/glenn-vernon-duke.png",record:"First season",scheme:"Blueprint offense",background:"They called him Kobe because he looked like the legend and once scored 81 in a Charlotte rec game—although the only surviving box score is written on a Bojangles napkin. Glenn later designed Duke's offense while wandering the lumber aisle at 2 a.m.",storyline:"Every formation is named after a power tool. Opponents still haven't solved the Cordless Drill, and NCAA officials refuse to inspect the Table Saw package."},
  {name:"Jordan Thomas",team:"Universidad México",role:"Head Coach",image:"assets/coaches/jordan-thomas-umx.png",record:"Inaugural season",scheme:"Expeditionary power spread",background:"Jordan crossed borders, oceans, and enough Marine obstacle courses to treat fourth-and-goal as light cardio. He accepted the UMX job after allegedly sketching the Panteras' first playbook on the back of an international flight safety card.",storyline:"UCLA is sending players, Mexico City is building a legend, and Jordan claims the altitude is merely a defensive coordinator who cannot be fired."},
  {name:"Sam Small",team:"Decision Pending",role:"Defending National Champion",image:"assets/coaches/sam-small-decision.png",record:"Reigning champ",scheme:"Law-and-order defense",background:"Sam transformed lessons from asset protection, corrections, and police work into the nation's strictest defense. His players say every missed assignment produces a case file, a witness interview, and mandatory film review under fluorescent lights.",storyline:"After winning the title, he sealed his next-school decision inside an evidence bag. The announcement reportedly requires three signatures, a notary, and one extremely dramatic television special."}
];
const lore=[
  {year:"Charlotte",title:"The Napkin Pact",body:"Jordan, Glenn, and Sam supposedly swear eternal brotherhood over a Bojangles napkin—the same disputed document containing Glenn's legendary 81-point box score and the first draft of Sam's championship defense."},
  {year:"The Marines",title:"Operation: Best Friend",body:"Dusty offers Jordan friendship so relentlessly it becomes a campaign with phases, logistics, and after-action reports. Jordan finally surrenders. The treaty has never been broken, though rivalry week routinely tests it."},
  {year:"The Family",title:"The Backyard Combine",body:"Chris grows up inside an unofficial coaching laboratory where cookouts become film sessions and every family argument ends with somebody drawing a route tree. Jordan serves as uncle, scout, and occasional target of the kid's trash talk."},
  {year:"The Dynasty",title:"The Headset Prophecy",body:"An allegedly cursed headset passes through the brotherhood. Whoever wears it can win a title—but must eventually defeat somebody from the circle. Sam won first. Now everyone wants the headset and nobody admits possessing it."}
];
const tickers=["THE DECISION: National champion Sam Small will choose a new school","#ChampsGoWhereTheyWant — Small's destination remains secret","HISTORY: Universidad México becomes NCAA's first non-U.S. member","Coach Jordan Thomas introduced as leader of the Panteras"];
document.querySelector('#story-grid').innerHTML=stories.map(s=>`<article class="story-card"><span class="category">${s.category}</span><h3>${s.title}</h3><p>${s.body}</p><span class="story-meta">${s.meta}</span></article>`).join('');
document.querySelector('#rankings-list').innerHTML=rankings.map(([p,t,r,tr])=>`<div class="rank-row"><span class="pos">${p}</span><b>${t}</b><small>${r}</small><span class="trend ${tr.includes('▲')?'up':tr.includes('▼')?'down':''}">${tr}</span></div>`).join('');
document.querySelector('#score-list').innerHTML=scores.map(([s,a,as,b,bs])=>`<article class="score-card"><span class="status">${s}</span><div class="score-team"><strong>${a}</strong><b>${as}</b></div><div class="score-team"><strong>${b}</strong><b>${bs}</b></div></article>`).join('');
document.querySelector('#player-grid').innerHTML=players.map(([r,n,s,y,td,q])=>`<article class="player-card" data-rank="${r}"><span class="school">${s}</span><h3>${n}</h3><p>Dynamic playmaker powering a championship run.</p><div class="stats"><span><b>${y}</b><small>Yards</small></span><span><b>${td}</b><small>TDs</small></span><span><b>${q}</b><small>${r===1?'Comp':'Rate'}</small></span></div></article>`).join('');
document.querySelector('#coach-grid').innerHTML=coaches.map(c=>`<article class="coach-card"><div class="coach-photo"><img src="${c.image}" alt="${c.name}, ${c.team} ${c.role}" loading="lazy"><span>${c.team}</span></div><div class="coach-copy"><p class="coach-role">${c.role}</p><h3>${c.name}</h3><p class="coach-background">${c.background}</p><div class="coach-facts"><span><small>Record</small><b>${c.record}</b></span><span><small>Identity</small><b>${c.scheme}</b></span></div><blockquote>“${c.storyline}”</blockquote></div></article>`).join('');
document.querySelector('#connection-map').innerHTML=`<span>Jordan</span><i>Charlotte</i><span>Glenn</span><i>Charlotte</i><span>Sam</span><i>Marines</i><span>Dusty</span><i>Family</i><span>Chris</span>`;
document.querySelector('#lore-grid').innerHTML=lore.map((l,i)=>`<article class="lore-card"><span class="lore-number">0${i+1}</span><p>${l.year}</p><h3>${l.title}</h3><div>${l.body}</div></article>`).join('');
const ticker=[...tickers,...tickers].map(t=>`<span>${t}</span>`).join('');document.querySelector('#ticker-track').innerHTML=ticker;
const now=new Date();document.querySelector('#date-stamp').textContent=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase();document.querySelector('#year').textContent=now.getFullYear();
const button=document.querySelector('.menu-button'),links=document.querySelector('.nav-links');button.addEventListener('click',()=>{const open=links.classList.toggle('open');button.setAttribute('aria-expanded',open)});links.addEventListener('click',()=>{links.classList.remove('open');button.setAttribute('aria-expanded','false')});
