const logos={"South Carolina":"assets/teams/south-carolina.png","Universidad México":"assets/umx/umx-temple-logo.png","BYU":"assets/teams/byu.png","Florida State":"assets/teams/florida-state.png","Washington":"assets/teams/washington.png"};
document.querySelector('.page-hero .eyebrow').textContent='2026 · After Week 2';document.querySelector('.national-poll .eyebrow').textContent='Week 2 poll';document.querySelector('.national-poll .poll-note').innerHTML='<strong>Commissioner-provided rankings after Week 2.</strong> BYU falls to No. 23; Florida State remains the highest-rated unbeaten user program outside the poll.';
const teams=[['1','Florida State','Glenn Vernon','2–0 · 76–36'],['2','South Carolina','Sam Small','1–0 · 70–31'],['3','BYU','Chris Cathcart','1–1 · No. 23 nationally'],['4','Universidad México','Jordan Thomas','1–1 · 41–77'],['5','Washington','Dusty Cathcart','0–1 · 21–57']];
const players=[['Ashton Daniels','QB','Florida State','566 pass yds · 1 pass TD; 1 rush TD'],['Quintrevion Wisner','HB','Florida State','292 rush yds · 6 TD'],['LaNorris Sellers','QB','South Carolina','417 pass yds · 5 TD'],['Nico Iamaleava','QB','Universidad México','500 pass yds · 4 TD'],['Bear Bachmeier','QB','BYU','595 pass yds · 7 TD'],['B. Hunt','WR','South Carolina','161 rec yds · 3 TD'],['Tiger Bachmeier','WR','BYU','153 Week 2 rec yds · 1 TD'],['S. McAllister','HB','South Carolina','65 rush yds · 4 TD'],['LJ Martin','HB','BYU','169 rush yds · 5 TD'],['B. Loftin','WR','Universidad México','13 rec · 164 yds · 2 TD']];
const mark=team=>`<span class="team-logo"><img src="${logos[team]}" alt="${team}"></span>`;
document.querySelector('#user-rankings').innerHTML=`<p class="preseason-note">User-team records are updated through the completed Week 2 games.</p><div class="ranking-table">${teams.map(([rank,team,coach,stat])=>`<div class="ranking-line"><span class="position">${rank}</span>${mark(team)}<span><b>${team}</b><small>${coach}</small></span><span class="stat">${stat}</span></div>`).join('')}</div>`;
document.querySelector('#player-rankings').innerHTML=`<p class="preseason-note">Top performances and cumulative leaders from the five user programs.</p><div class="ranking-table">${players.map(([name,position,team,stat],i)=>`<div class="ranking-line"><span class="position">${i+1}</span>${mark(team)}<span><b>${name} · ${team}</b><small>${position} · Through Week 2</small></span><span class="stat">${stat}</span></div>`).join('')}</div>`;

const nationalStats={
  Passing:[['B. Bachmeier · BYU','595 YDS · 7 TD'],['A. Daniels · Florida State','566 YDS · 1 TD'],['N. Iamaleava · Universidad México','500 YDS · 4 TD'],['L. Sellers · South Carolina','417 YDS · 5 TD'],['D. Williams Jr. · Washington','209 YDS · 2 TD']],
  Rushing:[['Q. Wisner · Florida State','292 YDS · 6 TD'],['LJ Martin · BYU','169 YDS · 5 TD'],['W. Knight · Universidad México','93 WEEK 2 YDS'],['S. McAllister · South Carolina','65 YDS · 4 TD']],
  Receiving:[['B. Loftin · Universidad México','164 YDS · 2 TD'],['B. Hunt · South Carolina','161 YDS · 3 TD'],['T. Bachmeier · BYU','153 WEEK 2 YDS · TD'],['D. Roebuck · Washington','86 YDS'],['D. Riles · Florida State','74 WEEK 2 YDS · TD']],
  Scoring:[['South Carolina','70.0 PPG · 1–0'],['BYU','46.0 PPG · 1–1'],['Florida State','38.0 PPG · 2–0'],['Washington','21.0 PPG · 0–1'],['Universidad México','20.5 PPG · 1–1']]
};
const statTabs=document.querySelector('#national-stat-tabs'),statBoard=document.querySelector('#national-stat-board');
document.querySelector('.national-stats .eyebrow').textContent='User-team leaderboard';document.querySelector('.national-stats h2').textContent='User Stats Ranked Head-to-Head';
const renderNationalStat=category=>{statTabs.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.category===category));statBoard.innerHTML=`<div class="national-leaderboard"><header><b>${category}</b><span>User programs only · through Week 2</span></header>${nationalStats[category].map(([name,stat],index)=>`<div><strong>${index+1}</strong><span>${name}</span><b>${stat}</b></div>`).join('')}</div>`};
statTabs.innerHTML=Object.keys(nationalStats).map((category,index)=>`<button class="${index?'':'active'}" data-category="${category}">${category}</button>`).join('');statTabs.addEventListener('click',event=>{const button=event.target.closest('button');if(button)renderNationalStat(button.dataset.category)});renderNationalStat('Passing');

document.querySelector('.defense-index .eyebrow').textContent='User programs only';document.querySelector('.defense-index h2').textContent='User Defense Rankings';
const defenseLogo=logos;
const defenses=[['Florida State','18.0 PPG allowed','Two wins and only 36 points allowed'],['BYU','29.5 PPG allowed','Strong first week followed by the Arizona collapse'],['South Carolina','31.0 PPG allowed','One game played; championship offense supplied separation'],['Universidad México','38.5 PPG allowed','Held Duke to seven after the difficult debut'],['Washington','57.0 PPG allowed','One completed game against BYU']];
document.querySelector('#defense-rankings').innerHTML=`<div class="defense-board">${defenses.map(([team,result,note],index)=>`<article><strong>${index+1}</strong><span class="team-logo"><img src="${defenseLogo[team]}" alt="${team}"></span><span><b>${team}</b><small>${note}</small></span><em>${result}</em></article>`).join('')}</div>`;
