const espn=id=>`https://a.espncdn.com/i/teamlogos/ncaa/500/${id}.png`;
const logos={"South Carolina":"assets/teams/south-carolina.png","Universidad México":"assets/umx/umx-temple-logo.png","BYU":"assets/teams/byu.png","Florida State":"assets/teams/florida-state.png","Washington":"assets/teams/washington.png",SMU:"assets/teams/smu.png",UMass:espn(113),UCF:espn(2116),Virginia:espn(258),Louisville:"assets/teams/louisville.png",Miami:"assets/teams/miami.png",Clemson:espn(228),"Boston College":espn(103),Pittsburgh:espn(221),"NC State":espn(152),Florida:"assets/teams/florida.png",Duke:espn(150),Purdue:espn(2509),Maryland:espn(120),Utah:"assets/teams/utah.png",Oregon:"assets/teams/oregon.png",Wisconsin:espn(275),"Michigan State":espn(127),Minnesota:espn(135),Illinois:espn(356),Michigan:"assets/teams/michigan.png",USC:"assets/teams/usc.png",Arizona:"assets/teams/arizona.png","FCS East":espn(0),TCU:espn(2628),"Iowa State":espn(66),"Arizona State":espn(9),Baylor:espn(239),Kansas:espn(2305),Cincinnati:espn(2132),"Mississippi State":espn(344),Alabama:"assets/teams/alabama.png",Kentucky:espn(96),Tennessee:"assets/teams/tennessee.png",Oklahoma:"assets/teams/oklahoma.png","Texas A&M":"assets/teams/texas-am.png",Arkansas:espn(8),Georgia:"assets/teams/georgia.png","Washington State":espn(265),Iowa:"assets/teams/iowa.png",Nebraska:espn(158),"Penn State":"assets/teams/penn-state.png",Indiana:"assets/teams/indiana.png"};
const g=(opponent,date,time,site='vs')=>({opponent,date,time,site});const bye=()=>({opponent:'BYE',date:'—',time:'Recharge',site:''});
const teams=[
{name:'South Carolina',coach:'Sam Small',color:'#73000a',note:'The reigning champion opens in Mexico City and closes at Clemson.',games:[g('Universidad México','Sep 5','3:30 PM','at'),bye(),g('Mississippi State','Sep 19','7:30 PM'),g('Alabama','Sep 26','12:00 PM','at'),g('Kentucky','Oct 3','7:30 PM'),g('Florida','Oct 10','3:00 PM','at'),g('BYU','Oct 17','3:30 PM','at'),g('Tennessee','Oct 24','7:30 PM'),g('Oklahoma','Oct 31','7:30 PM','at'),g('Texas A&M','Nov 7','7:30 PM'),g('Arkansas','Nov 14','12:00 PM','at'),g('Georgia','Nov 21','3:00 PM'),g('Clemson','Nov 28','7:30 PM','at')]},
{name:'Universidad México',coach:'Jordan Thomas',color:'#c79a24',note:'The first international NCAA schedule begins at home against the champion.',games:[g('South Carolina','Sep 5','3:30 PM'),g('Duke','Sep 12','3:30 PM','at'),g('Purdue','Sep 19','10:00 PM'),g('Maryland','Sep 26','4:00 PM','at'),g('Utah','Oct 3','5:45 PM'),g('Oregon','Oct 10','11:00 PM','at'),g('Wisconsin','Oct 17','11:00 PM'),g('Michigan State','Oct 24','3:30 PM'),bye(),g('Minnesota','Nov 7','7:30 PM','at'),g('Illinois','Nov 14','9:00 PM'),g('Michigan','Nov 21','7:00 PM','at'),g('USC','Nov 28','6:00 PM')]},
{name:'BYU',coach:'Chris Cathcart',color:'#002e5d',note:'The youngest coach gets his father in Week 1 and Sam in Week 7.',games:[g('Washington','Sep 5','10:15 PM'),g('Arizona','Sep 12','7:00 PM'),bye(),g('FCS East','Sep 26','2:15 PM'),g('TCU','Oct 3','2:30 PM','at'),g('Iowa State','Oct 9','10:00 PM'),g('South Carolina','Oct 17','3:30 PM'),g('UCF','Oct 24','12:00 PM','at'),g('Arizona State','Oct 31','7:00 PM'),g('Utah','Nov 7','3:30 PM','at'),g('Baylor','Nov 14','2:00 PM'),g('Kansas','Nov 21','2:00 PM','at'),g('Cincinnati','Nov 28','2:00 PM')]},
{name:'Florida State',coach:'Glenn Vernon',color:'#782f40',note:'Glenn’s first full season includes Miami, Clemson, and a Washington trip.',games:[g('SMU','Sep 7','6:00 PM'),g('UMass','Sep 12','3:15 PM'),g('UCF','Sep 19','1:00 PM','at'),bye(),g('Virginia','Oct 3','5:00 PM'),g('Louisville','Oct 9','7:00 PM','at'),g('Miami','Oct 17','3:30 PM','at'),g('Washington','Oct 24','3:30 PM','at'),g('Clemson','Oct 31','7:00 PM'),g('Boston College','Nov 7','12:00 PM','at'),g('Pittsburgh','Nov 13','7:00 PM','at'),g('NC State','Nov 21','3:30 PM'),g('Florida','Nov 28','8:00 PM')]},
{name:'Washington',coach:'Dusty Cathcart',color:'#4b2e83',note:'Dusty debuts against his son, then faces four more ranked preseason teams.',games:[g('BYU','Sep 5','10:15 PM','at'),bye(),g('Washington State','Sep 19','3:30 PM','at'),g('Minnesota','Sep 26','10:30 PM'),g('USC','Oct 3','10:30 PM','at'),g('Iowa','Oct 10','10:30 PM'),g('Purdue','Oct 17','12:00 PM','at'),g('Florida State','Oct 24','3:30 PM'),g('Nebraska','Oct 31','8:00 PM','at'),g('Penn State','Nov 7','10:30 PM'),g('Michigan State','Nov 14','12:00 PM','at'),g('Indiana','Nov 21','7:00 PM'),g('Oregon','Nov 28','3:00 PM','at')]}
];
teams[0].note='The champion survived an early Mexico City ambush and opened with 70 points.';teams[0].games[0].time='FINAL · W 70–31';teams[1].note='The Panteras led 21–7 in their historic debut before falling to the reigning champion.';teams[1].games[0].time='FINAL · L 31–70';teams[3].note='Glenn opened his Florida State tenure by beating No. 22 SMU behind four Wisner touchdowns.';teams[3].games[0].time='FINAL · W 31–20';
const userTeams=new Set(teams.map(t=>t.name));const tabs=document.querySelector('#schedule-tabs'),posters=document.querySelector('#schedule-posters');
tabs.innerHTML=teams.map((t,i)=>`<button class="${i?'':'active'}" data-team="${i}">${t.name}</button>`).join('');
posters.innerHTML=teams.map((t,i)=>`<article class="schedule-poster ${i?'':'active'}" style="--team:${t.color}"><div class="poster-brand"><img src="${logos[t.name]}" alt="${t.name}"><strong>2026 Schedule</strong><h2>${t.name}</h2><p>Head Coach · ${t.coach}</p><div class="poster-note">${t.note}</div></div><div class="schedule-grid">${t.games.map((x,w)=>`<div class="schedule-row ${x.opponent==='BYE'?'bye':''} ${userTeams.has(x.opponent)?'user-clash':''}"><span class="week">Week ${w+1}</span>${x.opponent==='BYE'?'<span></span>':`<img src="${logos[x.opponent]}" alt="${x.opponent}">`}<span><b>${x.opponent}</b><small>${x.opponent==='BYE'?'Open date':x.site==='at'?'Away':'Home'}</small></span><time>${x.date}<br>${x.time}</time></div>`).join('')}</div></article>`).join('');
tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));posters.querySelectorAll('.schedule-poster').forEach((x,i)=>x.classList.toggle('active',i===+b.dataset.team));posters.scrollIntoView({behavior:'smooth',block:'start'})});
